google/jaxopt

jaxopt/_src/bisection.py
jaxopt/_src/projection.py
tests/bisection_test.py

- Docstring improvements
- Set `init_params` to `None` by default
- Convert `lower` and `upper` to floats (see #16)

Bisection improvements.

---

examples/ridge_reg_implicit_diff.py

The current ridge regression example is broken with the following error:
```
TypeError: jax._src.scipy.sparse.linalg.cg() got multiple values for keyword argument 'x0'
```
I believe this stems from the fact that `linear_solve.solve_cg` takes `init` as opposed to `x0` as a named parameter
https://github.com/google/jaxopt/blob/e42a1ff6f80ca2a3dae5fa60c2a7fedad91d527c/jaxopt/_src/linear_solve.py#L109

Fix ridge regression example: change x0 to init in solve_cg

---

jaxopt/_src/base.py
jaxopt/_src/bisection.py
jaxopt/_src/block_cd.py
jaxopt/_src/gradient_descent.py
jaxopt/_src/mirror_descent.py
jaxopt/_src/optax_wrapper.py
jaxopt/_src/polyak_sgd.py
jaxopt/_src/projected_gradient.py
jaxopt/_src/proximal_gradient.py
jaxopt/_src/quadratic_prog.py
jaxopt/_src/scipy_wrappers.py
jaxopt/base.py

This PR implements several core changes.
1) Add an `implicit_diff_solve` option for specifying the linear solver to use for doing implicit diff (previously the `implicit_diff` served *both* the purpose of enabling/disabling implicit diff and of specifying the solver)
2) Add `jit` and `unroll` option to all solvers for finer-grained control on how the optimization loop is performed
3) Move `pre_update` to within `update` in `OptaxSolver` and `PolyakSGD` (fixes #27)
4) Reorganize and rename classes. Since Python is increasingly used as a typed language, it will be useful if we can create functions that accept a solver as argument
```
def some_func(solver: jaxopt.base.IterativeSolver):
```

Add implicit_diff_solve, jit, unroll options and reorganize base classes

---

jaxopt/_src/linear_solve.py
jaxopt/_src/quadratic_prog.py
tests/quadratic_prog_test.py

Changed the linear solver used  in _solve_eq_constrained_qp_KKT to gminres since the KKT is symmetric but not necessarily positive definite.  This is the recommend solver for this  type of KKT system in Nocedal & Wright, section 16.3, Numerical Optimization. 
I also tried solve_normal_cg instead, but it's convergence in residual is slow, and consequently fails the units test _check_derivative_A_and_b unless significantly increase tolerance (and number of iterations).

Quad solver fix

---

jaxopt/_src/tree_util.py
tests/tree_util_test.py

Fixes #44
1. Added a _vdot_safe product for computing tree_vdot (Mathieu's fix)
2. Added new test on pytrees that do not have arrays on leaves

fix for tree_vdot for when leaves are not arrays. 

---

docs/api.rst
docs/changelog.rst
docs/conf.py
docs/fixed_point.rst
docs/index.rst
docs/objective_and_loss.rst
examples/plot_anderson_accelerate_gd.py
examples/plot_picard_ode.py
jaxopt/_src/anderson.py
jaxopt/_src/objective.py
jaxopt/_src/picard.py
jaxopt/objective.py

I added documentation section for Fixed Point iteration solvers, including Picard Iterations and Anderson Acceleration.  
Those two features are illustrated with two examples (ODE solving and Gradienty descent speed up) contributing to sphynx-gallery.

Add Anderson doc, Picard ODE example, Anderson GD example.

---

docs/Makefile

The folder _autosummary/ generated need to be deleted too when cleaning, otherwise old .rst might pollute it.

clean _autosummary

---

jaxopt/_src/base.py
jaxopt/_src/gradient_descent.py
jaxopt/_src/implicit_diff.py
tests/gradient_descent_test.py

Instead of always relying on `optimality_fun` to carry the canonical signature for the solver, accept an optional canonical-signature function in `custom_root` and `custom_fixed_point`.
Check for a corresponding optional attribute on subclasses of `IterativeSolver` when run under implicit diff mode. Use this to indicate that `GradientDescent.fun` has the canonical signature for GD solvers.
Fixes #51

take optional reference signature for implicit diff

---

jaxopt/_src/linear_operator.py
jaxopt/_src/osqp.py
jaxopt/_src/quadratic_prog.py
jaxopt/_src/tree_util.py
tests/osqp_test.py
tests/quadratic_prog_test.py

First attempt to implement a general QP solver based on ADMM and heuristics of OSQP: https://arxiv.org/pdf/1711.08013.pdf
Solve problems of the form:
- suppports `l=-jnp.inf`, `u=jnp.inf` and `l=u`.
- arbitrary pytrees for `q, x` and `l, u, z` (as long they are compatible with each other).
- arbitrary matvecs for P and A (their input/output need to be compatible with pytrees `x,z`). Those matvecs can be parametrized by `params_P,params_A`.
- primal/dual infeasability detection (can be turn on/off for speed concerns).
- primal/dual variables computation.
- implicit differentiation wrt P (or params_P), q, A (or params_A), l, u.
- objective does not need to be _stricly_ convex (convex is sufficient), and constraints do not need to be linearly independant. Can be used for Linear Programming …

Add OSQP Jax implementation + tests.

---

jaxopt/_src/base.py
jaxopt/_src/cvxpy_wrapper.py
jaxopt/_src/eq_qp.py
jaxopt/_src/implicit_diff.py
jaxopt/_src/linear_operator.py
jaxopt/_src/osqp.py
jaxopt/_src/quadratic_prog.py
tests/cvxpy_wrapper_test.py
tests/eq_qp_test.py
tests/linear_operator_test.py
tests/osqp_test.py

!!! The goal of this PR is primarly discussions, not merging !!!
Four classes are available to perform QuadraticProgramming
| Class        | Matvec, Pytree  | vmap, jit, GPU | Precision | Stable | Input |  File           | 
| ---------- |:----------:| -----:|-----------:|-----------:|----------:|--------:|
| `QuadraticProgramming`     | variable | variable | variable | variable |  `((Q,c), (A,b), (G,h))` | quadratic_prog.py | 
| `CVXPY_QP`      |    No | No | High | Yes |  `((Q,c), (A,b), (G,h))` |  cvxpy_wrapper.py      |
| `OSQP` |  No | Yes |  Low | Yes |  `((Q,c), (A,b), (G,h))` | osqp.py | 
| `BoxOSQP` |   Yes | Yes |  Low | Yes | `((Q,c), A, (l,u))` | osqp.py |
| `EqualityConstraintsQP` |   Yes | Yes | Low | No | `((Q,c), (A, b))` |  equality_quadratic_prog.py |
The function …

Refactorize quadraticProg into CVXPY_QP, EqualityConstraintsQP.

---

jaxopt/_src/base.py
jaxopt/_src/cvxpy_wrapper.py
jaxopt/_src/eq_qp.py
jaxopt/_src/osqp.py
jaxopt/_src/polyak_sgd.py
jaxopt/_src/projected_gradient.py
jaxopt/_src/proximal_gradient.py
jaxopt/_src/quadratic_prog.py
jaxopt/_src/scipy_wrappers.py
tests/anderson_test.py

An issue was found whereby executing the `run` method of `IterativeSolver`s without `jit` would cause `lax.while_loop` or `lax.scan` to be retraced in each subsequence call. This was due to `cond_fun` and `body_fun` being (re)defined inside the private method `_run` of `IterativeSolver`.
The functions `cond_fun` and `body_fun` have been defined as methods of `IterativeSolver`. This solved the retracing issues. However, it causes two important changes in the way subclasses of `IterativeSolver` behave, namely
1. Methods of `IterativeSolver` must support serving as inputs to JAX transforms directly (see point below).
2. Positional and keyword arguments of `run` are no longer passed to `body_fun` with a closure but rather as explicit inputs. Hence, they must support JAX tracing.
We found that …

Prevent recompilation of loops in `solver.run` if executing without jit.

---

jaxopt/_src/base.py
jaxopt/_src/eq_qp.py
jaxopt/_src/iterative_refinement.py
jaxopt/_src/linear_operator.py
jaxopt/_src/linear_solve.py
jaxopt/_src/osqp.py
jaxopt/_src/tree_util.py
jaxopt/linear_solve.py
tests/eq_qp_test.py
tests/iterative_refinement_test.py
tests/linear_solve_test.py

The class `IterativeRefinement` is a wrapper to increases the precision of linear system solvers: by minimizing the residuals iteratively a high accuracy solution can be obtained from a low accuracy solver, which is useful in `float32` for ill-posed problems.
This functionnality is also available through a function in `linear_solve`, that mimic the interface of `solve_gmres,solve_bicgstab` etc...
Iterative Refinement solves `Ax=b` with the following recursion:
Where `x_0=0` and `r_0=b`. The matrix `A_bar` can be any (regularized) approximation of `A`. The linear solver on the first step can be inaccurate, as long as computing the residuals `b-Ax` is accurate.
The user can specify its own `A_bar`; otherwise we take `A_bar=A`.
This allows `EqualityConstrainedQP` to solve badly scaled …

IterativeRefinement to improve EqualityConstrainedQP speed

---

examples/deep_learning/flax_resnet.py

Most changes are geared towards ensuring we give strong and
efficient baselines by default, without parameter tuning. The most
dramatic gains are in the CIFAR* datasets.
Currently, the train/test accuracy for the different datasets with
default flags are:
- MNIST: 0.99/0.99 (this one didn't change much)
- FASHION_MNIST: 0.94/0.88 with a Time elapsed of 0:03:09
(vs 0.71/0.69 for previous defaults).
- E_MNIST: 0.85/0.85 with a Time elapsed of 0:25:56
(vs 0.31/0.37 for previous defaults).
- CIFAR10: 0.87/0.75 with Time elapsed of 0:02:36
(vs 0.23/0.22 for previous default architecture and
0.29/0.32 for resnet18).
- CIFAR100: 0.72/0.39, with a time elapsed: 0:02:31
(vs 0.07/0.06 for previous default architecture and
0.11/0.09 for resnet18).
Here, time elapsed is on a workstation with a …

ENH: make flax_resnet.py faster and more accurate across the board

---

docs/index.rst

I just realized that the citing information is only in the github README but not in the online documentation. It seems important to me to add it to the documentation, since non-dev users might never read the github README page

add citing information to the documentation

---

examples/constrained/binary_kernel_svm_with_intercept.py
examples/constrained/multiclass_linear_svm.py

The two examples of SVM `binary_kernel_svm_with_intercept` and `multiclass_linear_svm` are now solved with ``BoxOSQP`` and ``OSQP`` on toy datasets.
The `binary_kernel_svm_with_intercept` example also exhibit a `LinearKernel` class that illustrates a possible API for kernels. See also the (unmerged) branch: https://github.com/Algue-Rythme/jaxopt/blob/svmfast/jaxopt/_src/kernels.py

Add OSQP to SVMs examples.

---

docs/changelog.rst
jaxopt/_src/implicit_diff.py
tests/bisection_test.py

When a solver is sent through `custom_root`, we customize its derivative (via `jax.custom_vjp`) to make use of the implicit AD machinery. This change customizes all higher-order derivatives similarly.
Fixes #141 and adds a test for it.

customize the VJP of custom-root functions to higher order

---

jaxopt/_src/osqp.py
jaxopt/_src/projection.py
tests/fixed_point_iteration_test.py
tests/projection_test.py

Last steps in the removal of `QuadraticProgramming` class: replacing it by `OSQP` and `EqualityConstrainedQP` in `_src/projections.py`.
By default the function `projection_polyhedron` checks if the polyhedron is empty ([issue encountered by a user](https://github.com/google/jaxopt/issues/70#issuecomment-943701279)). This check is performed by raising an exception. This prevents the code of the projection to be jittable. `OSQP` offers ways to check feasability within `jit` block without raising an exception but by returning an error code in `state.status` instead. This can be left for future work.
In future PRs we could wrap projections in classes (instead of functions) to separate differentiable parameters and non differentiable hyper-parameters.

Remove QuadraticProg in projections

---

jaxopt/_src/osqp.py
jaxopt/_src/tree_util.py
jaxopt/tree_util.py
tests/tree_util_test.py

Fix minor bug on `tree_where` as mentioned [here](https://github.com/google/jaxopt/issues/144).

fix tree_where for singleton pytrees

---

jaxopt/_src/base.py
jaxopt/_src/loop.py
tests/base_test.py

Also avoid a redundant jit of `lax.while_loop` that unnecessarily restricts the loop trip count to be static.

support dynamic max iteration count in iterative solvers

---

examples/deep_learning/distributed_flax_imagenet.py

The purpose of this example is to illustrate how JAXopt solvers can be easily used for distributed training thanks to `jax.pjit`. In this case, we begin by implementing data parallel training of a `ResNet50` model on the `ImageNet` datasets as a fork of [Flax's official ImageNet example](https://github.com/google/flax/tree/main/examples/imagenet). General aspects to pay attention to include:
+ How auxiliary information (e.g. Flax mutables, model outputs from train metrics, etc) can be extracted from `loss_fun` using the `state.aux` field of JAXopt's optimizer state.
+ How `jax.pjit` can be used to easily port single-device training loops to distributed training loops.
Future examples will cover data and model parallel training using `jax.pjit` as well as support for `jax.pmap`-based …

Distributed Flax ImageNet example

---

jaxopt/_src/tree_util.py
jaxopt/tree_util.py
tests/tree_util_test.py

Generalizes `tree_util.tree_where` by allowing any of its arguments to be a leaf pytree (i.e. single array), including `cond`. The function `broadcast_pytree` was factored out of `tree_where`, as it could presumably be used in combination with other `tree_x`methods in `tree_util`.

Add support for leaf cond pytrees in `tree_util.tree_where`.

---

jaxopt/_src/scipy_wrappers.py
tests/scipy_wrappers_test.py

fixes #201 
We were essentially asserting that leaves are arrays by trying to read their `shape` and `dtype` attributes. I could imagine wanting to avoid `jnp` conversion (including device placement of scalar leaves). But those may be edge cases; worthwhile to at least handle them correctly for now.

convert pytree leaves to jax arrays to determine their shape/dtype

---

.github/workflows/tests.yml
setup.py

This officially adds Python 3.10 support.
I have used `jaxopt` with Python 3.10 without encountering any issues so far, so I expect that simply adding the classifier is the only change needed.
Python 3.10 is also added to CI testing. Let me know if there is something I have missed.
Fix #213

feat: add Python 3.10 support officially

---

jaxopt/_src/backtracking_linesearch.py
jaxopt/_src/lbfgs.py
tests/lbfgs_test.py

The test with line search on the Rosenbrock function is now passing. I've added a mechanism so that if the stepsize becomes less than `min_stepsize`, then we restart it. Unfortunately, it has to be done in every solver (`LBFGS`, `NonlinearCG`, ...) separately because we don't have an API mechanism to do it in `BacktrackingLinesearch`. If the gradient norm becomes too small, it may be better to disable line search and switch to constant stepsize but I haven't implemented it yet, as this would make the branch data-dependent.
CC @fabianp @junpenglao @Algue-Rythme

Ensure the stepsize doesn't become too small.

---

docs/changelog.rst
docs/quadratic_programming.rst
jaxopt/_src/linear_operator.py
jaxopt/_src/osqp.py
tests/osqp_test.py

Classes `OSQP` and `BoxOSQP` now support the (optional) parameter `fun`: a function promised to be a quadratic convex polynomial. Any function that can be written on the form `fun(x, params_Q)=0.5xQx+cx+cste` for some PSD matrix Q.
The advantages of matrix-vector products are leveraged to avoid the explicit computation of `Q` at any time.
Pros:
- easy writing of objective function for fast prototyping
- no need to disantangle quadratic `0.5xQx` and affine `cx+cste` terms: useful for least squares objectives: `||y-x||_2`
Cons:
- more calls to `jax.grad` are now required to retrieve `jnp.dot(c, x)` and to perform `Qx` matrix-vectors products
- this overhead _could_ be (partially) alleviated by an efficient XLA compiler with Common Sub Expression Elimination
First, I wanted to use the …

Convenience API for OSQP

---

benchmarks/lbfgs_benchmark.py
jaxopt/_src/lbfgs.py
jaxopt/_src/zoom_linesearch.py
tests/lbfgs_test.py
tests/zoom_linesearch_test.py

This PR is the first of a series of PRs to integrate zoom line search in JAXopt. It uses the code of @Joshuaalbert currently in JAX core. It supports only 1d arrays for parameters at the moment.
To be done in other PRs:
1) write more correctness tests, e.g. tests for isolated functions  such as `quadmin` or `cubicmin`
2) simplify the code when possible
3) add pytree support, either natively or via flattening
4) benchmarks: backtracking vs. zoom, SciPy vs. JAXopt on various problems (both convex and nonconvex) 
5) use our iterative solver API instead of using a lax.while_loop (this will give access to individual steps of the line search)
CC: @shoyer @jakevdp @junpenglao

Add zoom line search.

---

jaxopt/_src/lbfgs.py
jaxopt/_src/zoom_linesearch.py
tests/zoom_linesearch_test.py

`value_and_grad` is already computed within LBFGS so we save a compilation by not recomputing it within the zoom line search.

Support value_and_grad in zoom line search.

---

docs/conf.py

nbsphinx seems to be the right extension to display formulas from notebooks.
I removed the source_suffix list because of https://github.com/spatialaudio/nbsphinx/issues/310. So we shouldn't put ipynb in the extension list (to use nbsphinx), but if we just keep md and rst, the whole notebook appears raw.
I also had to remove the myst-nb extension that seemed in conflict with nbsphinx.

Allow formulas to be well displayed in html pages

---

jaxopt/_src/scipy_wrappers.py
tests/scipy_wrappers_test.py

`tol` is not parsed to `scipy.optimize.minimize` in `ScipyMinimize`.

Fix: parse tol to scipy minimize.

---

jaxopt/_src/lbfgs.py

This PR adds a new attribute to the `LBFGState` named tuple, `gamma`.
This attribute is needed when one wants to use the approximation of the Hessian inverse after the algorithm has run using `inv_hessian_product`.
Indeed I realized that in this implementation, the initial value of the approximation of the Hessian is recomputed at each iteration, as suggested by Nocedal (something that is not present in scipy to the best of my knowledge and understanding of Fortran).
The application I have in mind for the approximation of the Hessian inverse is https://arxiv.org/abs/2106.00553.
(I didn't write an issue first because it's such a small PR, and I was going to write this part anyway for my own xps)

Added `gamma` to `LBFGSState`

---

examples/implicit_diff/lasso_implicit_diff.py
examples/implicit_diff/ridge_reg_implicit_diff.py
examples/implicit_diff/sparse_coding.py

Currently on `main` the implicit diff examples have an error due to a missing state initialization (something noted [here](https://github.com/google/jaxopt/issues/235) as well although without a clear description).
For example for ridge regression:
```
Traceback (most recent call last):
File "/home/zramzi/workspace/jaxopt/examples/implicit_diff/ridge_reg_implicit_diff.py", line 94, in <module>
app.run(main)
File "/home/zramzi/workspace/jaxopt/venv/lib/python3.9/site-packages/absl/app.py", line 308, in run
_run_main(main, args)
File "/home/zramzi/workspace/jaxopt/venv/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
sys.exit(main(argv))
File "/home/zramzi/workspace/jaxopt/examples/implicit_diff/ridge_reg_implicit_diff.py", line 82, in main
state = solver.init_state(theta) …
```

Corrected the implicit diff examples

---

examples/deep_learning/flax_resnet.py

Fix bug introduced in https://github.com/google/jaxopt/commit/02bfdc2e2e9947611083b83b7bd1fc6783e3570d

Fix missing args,kwargs in resnet example

---

jaxopt/_src/lbfgs.py

This PR addresses the issue mentioned [here](https://github.com/google/jaxopt/discussions/322#discussioncomment-3824631), by allowing the user to decide if they want to have LBFGS fail when the line search fails or not using a `allow_line_search_fail` attribute (set to `False` by default to ensute backward compatibility).
I am not sure exactly which unit tests I should add for this new addition : typically it will fail on the Rosenbrock function.

Adding the possibility to stop LBFGS after a line search failure

---

jaxopt/_src/armijo_sgd.py

I also replaced "the authors" by the more explicit Vaswani et al. and cleaned up the citation

FIX typo recommanded -> recommanded

---

jaxopt/_src/lbfgs.py
tests/lbfgs_test.py

The feature I had introduced in https://github.com/google/jaxopt/pull/323 was failing when the run function was jitted and was a no-op when not because of the following reason:
```python
~True == -2  # this is True
```
Therefore when jitted it was complaining about different types in a condition function, and when not jitted it was equivalent to always being False.
EDIT
------
Actually I am still running into an error when jitted, so will continue to investigate.
The gist of the error is `Abstract tracer value encountered where concrete value is expected`, basically doing `(not self.stop_if_linesearch_fails | ~state.failed_linesearch)` is not allowed because one is a `bool` and the other is an abstract value.

Hot fix: corrected condition in lbfgs

---

docs/notebooks/implicit_diff/maml.ipynb
docs/notebooks/implicit_diff/maml.md

the underscore was insude the \mathcal command. It was actually rendering fine in mathjax, but it's wrong. I realized when copy pasting to latex.

FIX: wrong latex in maml.ipynb

---

jaxopt/_src/backtracking_linesearch.py
jaxopt/_src/bfgs.py
jaxopt/_src/lbfgs.py
jaxopt/_src/nonlinear_cg.py
jaxopt/_src/zoom_linesearch.py
tests/backtracking_linesearch_test.py
tests/zoom_linesearch_test.py

Linesearch methods affected : Backtracking linesearch and Zoom linesearch.
This was was also used in order to correct the way auxiliary values are handled in the BFGS, L-BFGS and Nonlinear CG solvers where these methods are used.
I still need to add tests on the matching between the auxiliary value and the parameters returned.

Added possibility for line search methods to return a potential auxiliary value in their results

---

jaxopt/_src/mirror_descent.py
jaxopt/_src/proximal_gradient.py
tests/gradient_descent_test.py
tests/projected_gradient_test.py
tests/proximal_gradient_test.py

This PR also gets rid of an extra computation done in the accelerated versions of GD and PGD that was needed to compute an old version of the error.
Added some unit tests to make sure there is no regression on number of calls for GD and PGD

removed extra computations in error computation for PGD, GD, and Mirror Descent

---

jaxopt/__init__.py
jaxopt/_src/base.py
jaxopt/_src/lbfgs.py
tests/lbfgs_test.py

This fixes #351 .
@mblondel I couldn't use your suggestion of creating a new type of init `LBFGSInit` because the `init_params` variable is used for both `init_state` and `update`. Therefore I would have had to add case distinctions in the 2 functions which seemed unreasonable.
Rather I took the approach I saw in some other iterative solvers which was to add an extra keyword argument to `init_state`, `update` and `_value_and_grad_fun`.
I added a test to make sure that this runs, but I am not sure whether we need to add a test to make sure that it improves some cases. I also don't know whether we should test that differentiation is ok.

Added a new API allowing to warm start the inverse Hessian approximation in LBFGS

---

tests/bisection_test.py

Internally in jaxopt, we (should) try to maintain that the parameters to a solver class are "static" from jax's point of view.
One reason for this is that class attributes might be read by any of the class' methods, including `run`. Meanwhile a bound `run` method serves as the solver function, which is passed through jaxopt's core `custom_root` mechanism in order to set it up with an implicit-diff-based custom VJP. Currently, that `custom_root` mechanism assumes that the solver function it receives has, in its closure, no arrays that are involved in any of jax's differentiation or staging. Re-stated using jax-internal jargon: `custom_root` assumes that the solver function it receives does not have tracers in its closure. But: a bound Python method (e.g. `o.run`) carries its bound instance …

avoid closing over dynamic jax tracers in the bisection solver

---

jaxopt/_src/scipy_wrappers.py
tests/scipy_wrappers_test.py

The `state` returned after running `ScipyMinimize` now contains the approximated inverse Hessian matrix (if the optimizer supports it, e.g. `'BFGS'`). The inverse Hessian matrix gives an approximation of the covariance matrix.
A small test has been added to check against original scipy. 
The goal is to solve issue #381.

Add inverse hessian approximation to the returned state

---

.github/workflows/tests.yml
setup.py

JAX requires at least Python 3.8

Drop Python 3.7 support.

---

.github/workflows/tests.yml
docs/api.rst
docs/root_finding.rst
jaxopt/__init__.py
jaxopt/_src/broyden.py
setup.py
tests/broyden_test.py

This PR adds the implementation of the good Broyden method (denoted in `scipy` as `'broyden1'`).
Some current pending aspects that I would like to discuss (and this is why I am opening this PR):
- I currently have a very hard time getting any test to pass when using float32, as numerical imprecisions cause nan and inf values to appear in my Broyden matrix computations. @mblondel if you have any idea on how to typically resolve those any input is welcome.
- I noticed that the setting of `gamma` is super important in many tests: maybe I should do like scipy and compute it if not set. Btw, unlike LBFGS I didnt find a rule to update it with iterations, so for now it is fixed.
- For now I rely on `jax` autodiff to perform the line search, whereas `scipy` computes an adhoc version of the …

Implemented (Good) Broyden

---

jaxopt/_src/armijo_sgd.py
jaxopt/_src/polyak_sgd.py

Add interpolation explanations for Polyak/Armijo API doc

---

docs/quadratic_programming.rst
jaxopt/_src/eq_qp.py
jaxopt/_src/osqp.py
tests/eq_qp_test.py
tests/osqp_test.py

New convenience API `fun` for EqualityConstrainedQP.
I also improved the documentation of Quadratic Programming in general, since several features were not properly documented. In particular we have four majors API for quadratic programming:
* dense matrices
* pytree of dense matrices (separable problems)
* matvecs
* quadratic fun
I documented those API with examples, and I added some unit-tests corresponding to the code given in documentation. I also added an "Implicit Differentiation pitfalls" section in quadratic programming, to illustrate a frequent mistake of users trying to differentiate their QP. This may be used in the future to answer questions or issues.
This should close issue #207

Extend convenience API for QP + doc

---

jaxopt/_src/anderson.py
tests/anderson_test.py

Add support for has_aux in AndersonAcceleration

---

jaxopt/_src/lbfgsb.py
tests/lbfgsb_test.py

Resolves #463 by correctly instantiating the function signature, and by adding the `self._grad_fun` alias.
Also adds a test to catch this is working (uses the example from #463).
(I've just signed the google CLA also!)

Fix lbfgsb grad when bounds are specified

---

jaxopt/_src/zoom_linesearch.py
tests/lbfgs_test.py

If the first trial of the zoom linesearch was NaN, no valid stepsize was found (returned 0 as final stepsize) and the solver would then get stuck. 
Fixed it by switching to zoom into 0 and first stepsize when a NaN or Inf is encountered during the search interval procedure.
Also fix the error to be inf even if it was nan. Otherwise the linesearch stops even if it could have further found a good stepsize.

Fix zoom to handle first trial infinite or NaN

---

jaxopt/_src/base.py
jaxopt/_src/lbfgs.py
jaxopt/_src/lbfgsb.py
jaxopt/_src/zoom_linesearch.py
tests/lbfgs_test.py
tests/zoom_linesearch_test.py

Fixed bug [409](https://github.com/google/jaxopt/issues/409), added corresponding test, enhanced debugging messages (for linesearch and solvers).

Fixed bug 409 due to bad handling of NaN values in zoom linesearch

---

.github/workflows/tests.yml
jaxopt/_src/levenberg_marquardt.py

Current workflow is not tested on python 3.11, which generated issues, see #476. This PR attempts to fix the typing issue and add tests on python 3.11.

Adding tests in python 3.11, fixing typing extension issue

---

jaxopt/_src/anderson.py
jaxopt/_src/armijo_sgd.py
jaxopt/_src/base.py
jaxopt/_src/bfgs.py
jaxopt/_src/bisection.py
jaxopt/_src/block_cd.py
jaxopt/_src/broyden.py
jaxopt/_src/fixed_point_iteration.py
jaxopt/_src/hager_zhang_linesearch.py
jaxopt/_src/iterative_refinement.py
jaxopt/_src/lbfgs.py
jaxopt/_src/lbfgsb.py
jaxopt/_src/mirror_descent.py
jaxopt/_src/nonlinear_cg.py
jaxopt/_src/polyak_sgd.py
jaxopt/_src/scipy_wrappers.py
jaxopt/_src/zoom_linesearch.py
tests/common_test.py
tests/zoom_linesearch_test.py

For now HZ-LS does not have the right elements in the state so it will fail in all solvers
Added num function/grad/ls eval in the following solvers:
- (L)-BFGS-(B): added num fun/grad/ls
- Anderson: added num fun
- Armijo SGD: for now armijo LS does not return the correct elements so difficult to do, esp. because the loops do not return the number of iterations done
- Bisection: added num fun
- BlockCD: added num fun/prox/grad
- Broyden: added num fun/ls
- FixedPointIteration: added num fun
- Gauss-Newton: not doable, because at some point linear solve does not return the number of iterations done. This comes down to `_cg_solve` returning only the final result.
- (Proximal/Projected)GradientDescent: the fista LS does not return the number of iterations done (same problem as Armijo)
- …

Adding num function/grad/prox/ls eval in solvers

---

jaxopt/_src/backtracking_linesearch.py
jaxopt/_src/hager_zhang_linesearch.py
jaxopt/_src/lbfgs.py
jaxopt/_src/tree_util.py
jaxopt/_src/zoom_linesearch.py
jaxopt/tree_util.py
tests/lbfgs_test.py
tests/linesearch_common_test.py
tests/tree_util_test.py

I started adding support for complex parameters, beginning with l-BFGS with zoom linesearch, see also issue #445.
The changes are rather straightforward and based on Sorber L, van Barel M, de Lathauwer L, Unconstrained Optimization of real functions in complex variables, SIAM J. Optim, Vol. 22, No. 3, pp. 879-898
* for some data, e.g., stepsize, change dtype to corresponding real dtype
* use complex conjugate of gradient for initial descent direction
* for dot products by vdot(x,y).real
* additionally, for testing, I made changes such that l-BFGS with zero history size falls back to gradient descent with linesearch
For real parameters these changes are removed when jitted, but could introduce some overhead without jitting. 
I plan to add support for more of the unbound optimizers and …

Support for complex parameter optimization

---

docs/notebooks/index.rst

Something must have changed in sphinx-gallery, because the the layout of this page had very ugly margins. This commit fixes that.
Before: 
Now:

Better layout for notebook gallery

---

jaxopt/_src/armijo_sgd.py
jaxopt/_src/optax_wrapper.py
jaxopt/_src/polyak_sgd.py
tests/common_test.py

The optax wrapper was not handling value_and_grad properly anymore due to the check of dtype in value (precisely at `value=jnp.asarray(jnp.inf, value.dtype)` where value was a tuple when `value_and_grad=True`) .
Here is a MWE. The fix is simple, I can add a test and review all similar calls of dtype of value if you want. (I needed this fix for a personal project but I can workaround).
```
import jax
from jax import numpy as jnp
from jaxopt import OptaxSolver
import optax
def fun(x): 
return 0.5*x**2
val_and_grad_fun = jax.value_and_grad(fun)
solver = OptaxSolver(val_and_grad_fun, opt=optax.sgd(learning_rate=0.1), value_and_grad=True)
solver.run(jnp.asarray(1.))
```

fix_optax_wrapper

---

jaxopt/_src/zoom_linesearch.py
tests/common_test.py
tests/zoom_linesearch_test.py

Used bitwise coding for warnings in zoom. Added quick test (see line 268 in zoom_linesearch_test.py). Previously the non-bitwise encoding of the flags was working because of the specific values used. 
Also, proximal solvers were not tested with verbose and the verbose test was running for any number of iterations, fixed it to 4 iterations to avoid unnecessary iterations (we just want to check the behavior not the result).

fix verbose in zoom, fix verbose test

---

jaxopt/_src/levenberg_marquardt.py
tests/levenberg_marquardt_test.py

this is just a simple update to the code to ensure that scalar function output are supported. Although less of interest, might be considered an edge case.

support scalar output in lm

---

docs/notebooks/deep_learning/adversarial_training.ipynb
docs/notebooks/deep_learning/adversarial_training.md
docs/notebooks/distributed/custom_loop_pjit_example.ipynb
docs/notebooks/implicit_diff/dataset_distillation.ipynb
docs/notebooks/implicit_diff/dataset_distillation.md
docs/notebooks/implicit_diff/maml.md
docs/notebooks/perturbed_optimizers/perturbed_optimizers.ipynb
docs/notebooks/perturbed_optimizers/perturbed_optimizers.md
docs/root_finding.rst

The current TPU activation code was throwing an error when TPUs are not available because new versions of JAX now throws a RuntimeError instead of a KeyError, as we were relying on before.

FIX: TPU activation error

---

jaxopt/_src/bfgs.py
jaxopt/_src/lbfgs.py
jaxopt/_src/zoom_linesearch.py
tests/bfgs_test.py
tests/lbfgs_test.py
tests/zoom_linesearch_test.py

Adding tests from jax to enable moving jax.optimize to using jaxopt, see https://github.com/google/jax/pull/17025. 
Tests failed with previous setup of maximal number of linesearch iterations fixed to 15 and pass by fixing it to 30.
Also, checked if lbfgs and bfgs tests could pass in x64 and added modifications and notes where necessary.
Note: an alternate fix would be to let the zoom linesearch make a step even it has not found a sufficient decrease. The failures were due to the fact that contrarily to scipy we do not "hope for the best" if the linesearch fails. But then this makes the optimizer possibly jump outside the domain of the objective (nan or inf). As long as we print a warning in this case (even without verbose), this could make sense too. Let me know what you prefer.

added jax tests and tested in x64, increased maxls for bfgs, lbfgs

---

.github/workflows/docs.yml
.github/workflows/tests.yml
docs/index.rst

This will build the documentation upon every push to master (not on unmerged pull requests) and push to https://jaxopt.github.io/dev/

Build and publish docs to GitHub Pages

---

jaxopt/_src/backtracking_linesearch.py
jaxopt/_src/base.py
jaxopt/_src/bfgs.py
jaxopt/_src/hager_zhang_linesearch.py
jaxopt/_src/lbfgs.py
jaxopt/_src/lbfgsb.py
jaxopt/_src/nonlinear_cg.py
jaxopt/_src/zoom_linesearch.py
tests/backtracking_linesearch_test.py

This implements the following:
1. Reduce number of gradient evaluations for BacktrackingLinesearch and generally use value_and_grad as a callable:
a. In BacktrackingLineSearch, one can pass a callable value_and_grad. In that case, now the armijo and goldstein conditions do not make unnecessary calls to gradients. They only need one call at initialization if the value or the gradient are not provided and one call at the end to output the value and gradient of the parameters found by the linesearch. I added a test to check if the number of calls to the gradients for those linesearches is indeed just 2.
b. I slightly updated ZoomLineSearch and HagerZhangLinesearches to have signatures using value_and_grad as callables (I simplified a bit HagerZhangLineSearch by the way). I propagated these …

Updated backtracking linesearch, allowed for value_and_grad callable in linesearches

---

jaxopt/_src/scipy_wrappers.py
tests/scipy_wrappers_test.py

This should fix #536 and #531 
Basically makes the `nfev` (function eval), `njev` (jacobian eval) and `nhev` (hessian eval) counts 0 if they are not present in the scipy results.
This was already the behaviour for the hessian.

made sure to use njev only when available in scipy optimize results

---

examples/constrained/nmf.py
examples/implicit_diff/lasso_implicit_diff.py
examples/implicit_diff/ridge_reg_implicit_diff.py

`load_boston` has been removed from scikit-learn since version 1.2 for ethical reasons.
This should fix the issue for the docs to build.

fix deprecated load_boston from scikitlearn

---

jaxopt/_src/anderson.py
jaxopt/_src/anderson_wrapper.py
jaxopt/_src/armijo_sgd.py
jaxopt/_src/backtracking_linesearch.py
jaxopt/_src/base.py
jaxopt/_src/bfgs.py
jaxopt/_src/bisection.py
jaxopt/_src/block_cd.py
jaxopt/_src/broyden.py
jaxopt/_src/cd_qp.py
jaxopt/_src/fixed_point_iteration.py
jaxopt/_src/gauss_newton.py
jaxopt/_src/gradient_descent.py
jaxopt/_src/hager_zhang_linesearch.py
jaxopt/_src/iterative_refinement.py
jaxopt/_src/lbfgs.py
jaxopt/_src/lbfgsb.py
jaxopt/_src/levenberg_marquardt.py
jaxopt/_src/mirror_descent.py
jaxopt/_src/nonlinear_cg.py
jaxopt/_src/optax_wrapper.py
jaxopt/_src/osqp.py
jaxopt/_src/polyak_sgd.py
jaxopt/_src/projected_gradient.py
jaxopt/_src/proximal_gradient.py
jaxopt/_src/zoom_linesearch.py
tests/common_test.py
tests/zoom_linesearch_test.py

Replaced "Error" by specific name of error considered and added other information when verbose=True.
Should be useful for debugging more quickly.
All verbose are now boolean too (some were int).

expanded verbose for all algorithms, made verbose a boolean for all algorithms

---

.github/workflows/tests.yml
setup.py

Jax no longer supports 3.8 (and will drop 3.9 in July according to their [deprecation policy](https://jax.readthedocs.io/en/latest/deprecation.html)).

Drop Python 3.8

---

jaxopt/_src/base.py
jaxopt/_src/bfgs.py
jaxopt/_src/broyden.py
jaxopt/_src/lbfgs.py
jaxopt/_src/lbfgsb.py
jaxopt/_src/nonlinear_cg.py
jaxopt/_src/osqp.py
tests/common_test.py

Fix https://github.com/google/jaxopt/issues/571, added tests.

Fix print for verbose=False

---

jaxopt/_src/prox.py
tests/prox_test.py

First of all, thanks for the very nice package.
In this PR I am generalizing the behavior of `jaxopt.prox.prox_lasso` to handle scalar input when jit-compiled. 
In particular the following used to result in an exception.
```python
import numpy as np
from jaxopt import prox
import jax
rng = np.random.RandomState(0)
x = (rng.rand(20) * 2 - 1, rng.rand(20) * 2 - 1)
jax.jit(prox.prox_lasso)(x, 0.5)
```
Best regards,
Edoardo

fix lasso with scalar l1reg

---

jaxopt/_src/osqp.py

The combined usage of [`Pytree of matrices API`](https://jaxopt.github.io/stable/quadratic_programming.html#pytree-of-matrices-api) and [`Quadratic function API`](https://jaxopt.github.io/stable/quadratic_programming.html#quadratic-function-api) is currently broken due to a missing operation performed on generic pytrees. This PR updates the operation to be performed with the existing pytree helpers.

Fix `BoxOSQP` when configured with `fun` and used with pytree-based APIs
